apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-analysis-service
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-analysis-service
  template:
    metadata:
      labels:
        app: tracking-analysis-service
    spec:
      containers:
        - name: tracking-analysis-service
          image: 'rannybal2024/tracking-analysis-service:latest'
          ports:
            - containerPort: 8091
              protocol: TCP
          env:
            - name: FRONTEND_URL
              value: 'https://nimble.kolayam.co.uk/'
            - name: INDEXING_SERVICE_URL
              value: 'http://indexing-service'
            - name: INDEXING_SERVICE_PORT
              value: '8080'
            - name: EUREKA_SERVICE_URL
              value: 'http://service-discovery:8761/eureka'
            - name: NIMBLE_INSTANCE_NAME
              value: tracking-analysis-service
            - name: DELEGATE_SERVICE_BASE_URL
              value: 'http://tracking-analysis-service'
            - name: DELEGATE_SERVICE_PORT
              value: '9265'
            - name: CONFIG_SERVER_URI
              value: 'http://config-server:8888'
            - name: CONFIG_SERVER_FAILFAST
              value: 'true'
            - name: DISCOVERY_ENABLED
              value: 'true'
            - name: DISCOVERY_SERVER_URI
              value: 'http://service-discovery:8761'
            - name: DISCOVERY_PREFER_IP
              value: 'false'
            - name: IDENTITY_SERVICE_URL
              value: 'http://identity-service:9096'
            - name: BUSINESS_PROCESS_SERVICE_URL
              value: 'http://business-process-service:8081'
            - name: DATAAGGREGATION_SERVICE_URL
              value: 'http://tracking-analysis-service:8091'
            - name: CATALOGUE_SERVICE_URL
              value: 'http://catalog-service-srdc:8095'
          resources:
            limits:
              memory: 2000Mi
              cpu: 800m
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600